export const FETCH_PHOTO_REQUEST = "FETCH_PHOTO_REQUEST"
export const FETCH_PHOTO_SUCCESS = "FETCH_PHOTO_SUCCESS"
export const FETCH_PHOTO_FAILURE = "FETCH_PHOTO_FAILURE"

export const UPDATE_SEARCH_ITEM = "UPDATE_SEARCH_ITEM"
export const UPDATE_START_PAGE = 'UPDATE_START_PAGE'
export const UPDATE_TOTAL_PAGE = "UPDATE_TOTAL_PAGE"